name: Checkout repo and setup Node
description: realm_web composite action for setting up jobs

inputs:
  token:
    description: alternative GitHub token
    required: false
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.token }}

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        always-auth: true
        cache: npm
        node-version-file: .nvmrc
        registry-url: https://npm.pkg.github.com
        scope: "@haliphax"

    - name: Install Node dependencies
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.token }}
      run: npm ci
