repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.0
    hooks:
      # blocks files larger than 500 KB
      - id: check-added-large-files

      # blocks files with leftover merge conflict markers
      - id: check-merge-conflict

      - id: no-commit-to-branch
        name: Block commits to main branch

  - repo: local
    hooks:
      - id: prettier
        name: Format files with prettier
        args: [prettier, -l, -u, -w]
        entry: npx
        language: system
        types: [text]
