name: Checks

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]

  push:
    branches: [main]

  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.branch }}

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: realm-ttrpg/web-interface/.github@main

      - name: ESLint
        run: npx eslint .

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: realm-ttrpg/web-interface/.github@main

      - name: Prettier
        run: npx prettier -lu .
