name: Publish site

on:
  push:
    branches: [main]

  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: publish-site

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          always-auth: true
          cache: npm
          node-version-file: .nvmrc
          registry-url: https://npm.pkg.github.com
          scope: "@haliphax"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Build site
        run: npm run build

      - name: Relative URLs
        run: sed -i -e 's/="\//="/g' html/*.html

      - uses: actions/upload-pages-artifact@v2
        with:
          path: html/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - id: deployment
        uses: actions/deploy-pages@v2
